### ISSUE TITLE
not able to deploy the trained model

### ISSUE THREAD

**Issue by mouhannadali** [aws-samples/amazon-sagemaker-tensorflow-object-detection-api#1]
I am not able to deploy the model after training

if I run
estimator.deploy(initial_instance_count=1, instance_type='ml.m5.xlarge')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-ce76a0806ab7> in <module>
----> 1 estimator.deploy(initial_instance_count=1, instance_type='ml.m5.xlarge')

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, use_compiled_model, wait, model_name, kms_key, data_capture_config, tags, **kwargs)
    789             model = self.create_model(**kwargs)
    790 
--> 791         model.name = model_name
    792 
    793         return model.deploy(

AttributeError: 'NoneType' object has no attribute 'name'

**If I run the deploy_endpoint.ipynb notebook (setting the model_artefact= s3://.../summaries/tf2-object-detection-2020-12-01-23-34-23-954/tensorboard-output/**

**I got the following error**

ClientError                               Traceback (most recent call last)
<ipython-input-9-bcc69978ba22> in <module>
----> 1 predictor = model.deploy(initial_instance_count=1, instance_type='ml.m5.xlarge')

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/model.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, update_endpoint)
    234             wait=wait,
    235             data_capture_config=data_capture_config,
--> 236             update_endpoint=update_endpoint,
    237         )
    238 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, **kwargs)
    506                 self._base_name = "-".join((self._base_name, compiled_model_suffix))
    507 
--> 508         self._create_sagemaker_model(instance_type, accelerator_type, tags)
    509         production_variant = sagemaker.production_variant(
    510             self.name, instance_type, initial_instance_count, accelerator_type=accelerator_type

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/model.py in _create_sagemaker_model(self, instance_type, accelerator_type, tags)
    178             vpc_config=self.vpc_config,
    179             enable_network_isolation=enable_network_isolation,
--> 180             tags=tags,
    181         )
    182 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in create_model(self, name, role, container_defs, vpc_config, enable_network_isolation, primary_container, tags)
   2423 
   2424         try:
-> 2425             self.sagemaker_client.create_model(**create_model_request)
   2426         except ClientError as e:
   2427             error_code = e.response["Error"]["Code"]

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             error_code = parsed_response.get("Error", {}).get("Code")
    675             error_class = self.exceptions.from_code(error_code)
--> 676             raise error_class(parsed_response, operation_name)
    677         else:
    678             return parsed_response

ClientError: An error occurred (ValidationException) when calling the CreateModel operation: Could not find model data at s3://tech-vision-ali/summaries/tf2-object-detection-2020-12-01-23-34-23-954/tensorboard-output/.

**Comment by sofianhamiti** [comment]
You should use the model.tar.gz S3 location in `model_artefact = '<your-model-s3-path>'` instead of tensorboard output.
See reference from the SageMaker Python SDK [documentation](https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/using_tf.html#deploying-directly-from-model-artifacts)

The easiest way to find the model.tar.gz S3 location is to look at your training job details in the SageMaker Console page.
You can find it under the "Output" section towards the bottom of the page.

Can you try and confirm if this worked?

**Comment by mouhannadali** [comment]
Hi, I couldnt find any model.tar.gz file in any of my S3 buckets (it might be due to a permission issue, no file were created)
however, I specified the output_path when creating the estimator as the following:
estimator = CustomFramework(image_uri=container,
                            role=role,
                            entry_point='run_training.sh',
                            source_dir='source_dir/',
                            instance_count=1,
                            output_path = '**_s3://your_output_path_**',
                            instance_type='ml.p3.8xlarge',
                            hyperparameters=hyperparameters,
                            tensorboard_output_config=tensorboard_output_config,
                            base_job_name='tf2-object-detection')

and now it is working properly
