### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by bonzoq** [aws-samples/amazon-sagemaker-tensorflow-object-detection-api#14]
I get the following error:

`
Error for Processing job tf2-object-detection-2021-06-10-13-17-37-173: Failed. Reason: ClientError: API error (404): manifest for 757901089955.dkr.ecr.us-west-2.amazonaws.com/tfrecord-processing:20210610131649 not found: manifest unknown: Requested image not found
`

Does this mean that an image is no longer available?

**Comment by bonzoq** [comment]
Before that error I get this warning:

Waiting g denied: User: arn:aws:sts::757901089955:assumed-role/AmazonSageMaker-ExecutionRole-20210607T223583/SageMaker is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-west-2:757901089955:repository/tfrecord-processing

**Comment by sofianhamiti** [comment]
Can you verify the permissions of the IAM role used in your notebook instance.
This seems to be: AmazonSageMaker-ExecutionRole-20210607T223583
Does it have permissions for pushing/pulling images to ECR?

**Comment by bonzoq** [comment]
This notebook has a role with the policy AmazonSageMakerFullAccess, which turns out to be insufficient. After adding EC2InstanceProfileForImageBuilderECRContainerBuilds policy the problem has been solved. Thank you!

**Comment by shreypareek1991** [comment]
@bonzoq Can you please share where and how you added this? I understand it should be in the JSON, but I have been unable to get it to work.
