### ISSUE TITLE
Error while making predictions ,input mismatch 

### ISSUE THREAD

**Issue by ipshita-saxena** [aws-samples/amazon-sagemaker-tensorflow-object-detection-api#17]
I have deployed tensorflow model , while doing predictions on images im getting this error  

An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{
    "error": "2 root error(s) found.\n  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,20,20,256] vs. shape[1] = [1,26,26,256]\n\t [[{{node functional_1/tf_op_layer_concat_6/concat_6}}]]\n\t [[StatefulPartitionedCall/_1121]]\n  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,20,20,256] vs. shape[1] = [1,26,26,256]\n\t [[{{node functional_1/tf_op_layer_concat_6/concat_6}}]]\n0 successful operations.\n0 derived errors ignored."
}".

**Comment by sofianhamiti** [comment]
Hi @ipshita-saxena, i have updated the repo with new TF version.
Can you have a try and confirm it works now?
