### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by sina-4** [aws-samples/amazon-sagemaker-tensorflow-object-detection-api#19]
This error comes when I create the endpoint 
update_endpoint is a no-op in sagemaker>=2.
How can I solve this problem please ?

**Comment by sofianhamiti** [comment]
Hi @Anis-kabli, this is a warning and doesn't cause the deployment the fail.
See more details here https://sagemaker.readthedocs.io/en/stable/v2.html
