### ISSUE TITLE
update_endpoint is a no-op in sagemaker>=2.

### ISSUE THREAD

**Issue by ghost** [aws-samples/amazon-sagemaker-tensorflow-object-detection-api#20]
I'm getting this error whenever I try to deploy : 
update_endpoint is a no-op in sagemaker>=2.
Can you help me to solve this please ?

**Comment by sofianhamiti** [comment]
Hi @sinatimelapse, this is a warning and doesn't cause the deployment the fail.
See more details here https://sagemaker.readthedocs.io/en/stable/v2.html
